name = "oi-bingo"
main = "Source/index.ts"
compatibility_date = "2023-12-06"
assets = { directory = "./public" }

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "oi-bingo"
database_id = "6fa63161-e18b-4386-bba6-983733aa9b88"
