// DO NOT MODIFY THIS FILE OR YOUR CHANGES WILL BE LOST!
// This file is generated by GenerateHTML.sh
// Last generated on Sat Jul 13 11:03:24 CST 2024

import File0 from './HTML/CYEZOI.png';
import File1 from './HTML/Home.html';
import File2 from './HTML/Home.js';
import File3 from './HTML/Login.html';
import File4 from './HTML/Login.js';
import File5 from './HTML/Logout.html';
import File6 from './HTML/Logout.js';
import File7 from './HTML/Register.html';
import File8 from './HTML/Register.js';
import File9 from './HTML/Settings.html';
import File10 from './HTML/Settings.js';
import File11 from './HTML/Users.html';
import File12 from './HTML/Users.js';
import File13 from './HTML/index.css';
import File14 from './HTML/index.html';
import File15 from './HTML/index.js';

const StaticFiles = {
    'CYEZOI.png': File0,
    'Home.html': File1,
    'Home.js': File2,
    'Login.html': File3,
    'Login.js': File4,
    'Logout.html': File5,
    'Logout.js': File6,
    'Register.html': File7,
    'Register.js': File8,
    'Settings.html': File9,
    'Settings.js': File10,
    'Users.html': File11,
    'Users.js': File12,
    'index.css': File13,
    'index.html': File14,
    'index.js': File15,
};

export class HTML {
    private Path: string;
    constructor(Path: string) {
        this.Path = Path;
    }

    public Process(): object {
        let ResponseData = {
            Data: '',
            ContentType: 'text/plain',
        };
        if (this.Path in StaticFiles) {
            ResponseData.Data = StaticFiles[this.Path];
            if (this.Path.endsWith('.html')) {
                ResponseData.ContentType = 'text/html';
            } else if (this.Path.endsWith('.js')) {
                ResponseData.ContentType = 'text/javascript';
            } else if (this.Path.endsWith('.css')) {
                ResponseData.ContentType = 'text/css';
            }
        }
        else {
            ResponseData.Data = '404 Not Found';
        }
        return ResponseData;
    }
}
